channels:
- anaconda
- conda-forge
dependencies:
- python=3.10.11
- pip=23.0.1
- pip:
   # Dependencies for Ray on AML
   - azureml-mlflow
   - azureml-defaults
   # - mlflow==1.27.0
   - mlflow==2.4.1
   - mlflow-skinny==2.4.1
   - ray-on-aml
   - ray[data]==2.5.0
   - ray[rllib]==2.5.0
   # Deps for RLlib
   - torch==2.0.1
   - tensorflow==2.11.1
   - tensorflow-probability==0.19.0
   - tensorboardX==2.2
   - torch==2.0.1
   # Dependencies for the sample
   - gymnasium
   - numpy==1.24.3
