channels:
- anaconda
- conda-forge
dependencies:
- python=3.10.11
- pip=23.0.1
- pip:
   # Dependencies for Ray on AML
   - azureml-mlflow
   - azureml-defaults
   - ray-on-aml
   - ray[data,rllib]==2.5.0
   # Deps for RLlib
   - torch==2.0.1
   # Dependencies for the Simple Adder
   - gymnasium==0.26.3
   - numpy==1.24.3
